version: '3.8'

services:
  llm-api:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=microsoft/DialoGPT-medium
      - MAX_LENGTH=512
      - LOG_LEVEL=INFO
    volumes:
      - model_cache:/root/.cache/huggingface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model_cache:
  